spring.datasource.url=jdbc:h2:file:d:/tmp/myApplicationDb2;AUTO_SERVER=TRUE
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver

spring.mail.host=mail4.hostinguk.net
spring.mail.port=465
spring.mail.username=jason@jasonmarston.me.uk
spring.mail.password=M0r5T0n!!

spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.socketFactory.class = javax.net.ssl.SSLSocketFactory